<a href="https://colab.research.google.com/github/ismachy/Introduction-to-ML/blob/main/HW4_Q2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
housing = pd.DataFrame(pd.read_csv("Housing.csv"))
housing.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [3]:
m = len(housing)
m

545

In [4]:
housing.shape

(545, 13)

In [5]:
# List of variables to map
varlist = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

# Defining the map function
def binary_map(x):
    return x.map({'yes': 1, "no": 0})

# Applying the function to the housing list
housing[varlist] = housing[varlist].apply(binary_map)

# Check the housing dataframe now
housing.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

  furnishingstatus  
0        furnished  
1        furnished  
2   semi-furnished  
3        furnished  
4        furnished

In [6]:

from sklearn.model_selection import train_test_split
np.random.seed(0)
# split 80% as training set and 20% as testing set
df_train, df_test = train_test_split(housing, train_size = 0.8, test_size = 0.2, random_state = 100)

df_train.shape

(436, 13)

In [7]:
df_test.shape

(109, 13)

In [8]:
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'price']
df_Newtrain = df_train[num_vars]
df_Newtest = df_test[num_vars]
df_Newtrain.head()

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
22   8050         3          1        1         1          1         1   
41   6360         3          2        4         1          0         0   
91   6750         2          1        1         1          1         1   
118  6420         3          1        1         1          0         1   
472  3630         4          1        2         1          0         0   

     hotwaterheating  airconditioning  parking  prefarea    price  
22                 0                1        1         0  8645000  
41                 0                1        0         1  7840000  
91                 0                0        2         1  6419000  
118                0                1        0         1  5950000  
472                0                0        3         0  3010000

In [9]:
df_Newtrain.shape

(436, 12)

In [10]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()
df_Newtrain[num_vars] = scaler.fit_transform(df_Newtrain[num_vars])
df_Newtrain.head(20)

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
22   0.432609       0.4   0.000000  0.000000       1.0        1.0       1.0   
41   0.314954       0.4   0.333333  1.000000       1.0        0.0       0.0   
91   0.342105       0.2   0.000000  0.000000       1.0        1.0       1.0   
118  0.319131       0.4   0.000000  0.000000       1.0        0.0       1.0   
472  0.124896       0.6   0.000000  0.333333       1.0        0.0       0.0   
344  0.140212       0.2   0.000000  0.000000       1.0        0.0       0.0   
1    0.495962       0.6   1.000000  1.000000       1.0        0.0       0.0   
257  0.446533       0.4   0.000000  0.000000       1.0        0.0       0.0   
184  0.081036       0.4   0.333333  0.333333       1.0        1.0       1.0   
275  0.152882       0.2   0.000000  0.000000       1.0        0.0       1.0   
290  0.053885       0.6   0.666667  0.333333       0.0        0.0       0.0   
43   0.289891       0.6   0.333333  1.000000       1.0        0.0       0.0   
398  0.089390       0.4   0.000000  0.333333       1.0        0.0       0.0   
390  0.020816       0.4   0.333333  0.333333       0.0        0.0       0.0   
133  0.206349       0.4   0.000000  0.666667       1.0        0.0       0.0   
136  0.248120       0.6   0.333333  0.333333       1.0        0.0       0.0   
157  0.068296       0.6   0.333333  0.333333       0.0        1.0       1.0   
461  0.217488       0.2   0.000000  0.000000       1.0        0.0       1.0   
450  0.112364       0.4   0.000000  0.333333       1.0        0.0       1.0   
23   0.189641       0.4   0.333333  0.333333       1.0        1.0       1.0   

     hotwaterheating  airconditioning   parking  prefarea     price  
22               0.0              1.0  0.333333       0.0  0.596970  
41               0.0              1.0  0.000000       1.0  0.527273  
91               0.0              0.0  0.666667       1.0  0.404242  
118              0.0              1.0  0.000000       1.0  0.363636  
472              0.0              0.0  1.000000       0.0  0.109091  
344              0.0              0.0  0.000000       0.0  0.181818  
1                0.0              1.0  1.000000       0.0  0.909091  
257              0.0              0.0  0.000000       0.0  0.236364  
184              0.0              0.0  0.000000       0.0  0.290909  
275              0.0              0.0  0.000000       0.0  0.222424  
290              0.0              0.0  0.000000       0.0  0.212121  
43               0.0              0.0  0.666667       0.0  0.515152  
398              0.0              0.0  0.333333       0.0  0.151515  
390              0.0              0.0  0.000000       0.0  0.151515  
133              0.0              1.0  0.000000       0.0  0.351515  
136              0.0              1.0  0.666667       0.0  0.345455  
157              0.0              0.0  0.333333       0.0  0.324242  
461              0.0              1.0  0.000000       0.0  0.115152  
450              0.0              0.0  0.000000       0.0  0.121212  
23               0.0              1.0  0.333333       0.0  0.596970

In [11]:
df_Newtest[num_vars] = scaler.fit_transform(df_Newtest[num_vars])
df_Newtest.head(20)

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
265  0.088172  0.333333        0.0  0.333333       1.0        0.0       0.0   
54   0.311828  0.333333        0.5  0.333333       1.0        1.0       0.0   
171  0.617849  0.333333        0.0  0.000000       1.0        0.0       0.0   
244  0.263082  0.333333        0.0  0.333333       1.0        1.0       1.0   
268  0.236559  0.666667        0.0  0.333333       1.0        0.0       0.0   
231  0.191398  0.333333        0.0  0.000000       1.0        0.0       0.0   
25   0.350538  0.666667        0.5  0.333333       1.0        1.0       1.0   
169  0.350538  0.666667        0.5  0.333333       0.0        0.0       0.0   
494  0.369176  0.000000        0.0  0.000000       1.0        0.0       0.0   
120  0.350538  0.333333        0.0  0.000000       1.0        1.0       1.0   
368  0.286022  0.000000        0.0  0.000000       0.0        0.0       0.0   
78   0.290323  0.333333        0.0  0.000000       1.0        1.0       1.0   
523  0.081505  0.666667        0.5  0.333333       1.0        0.0       0.0   
125  1.000000  0.333333        0.0  0.000000       1.0        0.0       0.0   
150  0.249892  0.333333        0.0  0.333333       1.0        1.0       1.0   
195  0.197849  0.666667        1.0  0.333333       1.0        0.0       1.0   
3    0.419355  0.666667        0.5  0.333333       1.0        0.0       1.0   
272  0.173835  0.333333        0.0  0.000000       1.0        1.0       1.0   
40   0.351254  0.333333        0.0  0.333333       1.0        0.0       1.0   
117  0.146953  0.666667        0.0  0.333333       1.0        1.0       0.0   

     hotwaterheating  airconditioning   parking  prefarea     price  
265              0.0              0.0  0.000000       1.0  0.248485  
54               0.0              1.0  0.333333       0.0  0.531987  
171              0.0              0.0  0.333333       1.0  0.329966  
244              0.0              0.0  0.000000       1.0  0.262626  
268              0.0              1.0  0.000000       0.0  0.246465  
231              0.0              0.0  0.000000       1.0  0.276094  
25               0.0              1.0  0.666667       1.0  0.646465  
169              0.0              1.0  0.000000       0.0  0.329966  
494              0.0              0.0  0.000000       0.0  0.087542  
120              0.0              0.0  0.666667       1.0  0.397306  
368              0.0              0.0  0.000000       0.0  0.178451  
78               0.0              1.0  0.666667       1.0  0.464646  
523              0.0              0.0  0.000000       0.0  0.053872  
125              0.0              1.0  0.666667       0.0  0.396633  
150              0.0              1.0  0.000000       1.0  0.363636  
195              0.0              0.0  0.666667       0.0  0.303030  
3                0.0              1.0  1.000000       1.0  1.000000  
272              0.0              0.0  0.666667       0.0  0.242424  
40               0.0              1.0  0.000000       1.0  0.582492  
117              0.0              1.0  0.000000       0.0  0.397306

In [12]:
y_Newtrain = df_Newtrain.pop('price')
X_Newtrain = df_Newtrain

In [13]:
X_Newtrain.head()

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
22   0.432609       0.4   0.000000  0.000000       1.0        1.0       1.0   
41   0.314954       0.4   0.333333  1.000000       1.0        0.0       0.0   
91   0.342105       0.2   0.000000  0.000000       1.0        1.0       1.0   
118  0.319131       0.4   0.000000  0.000000       1.0        0.0       1.0   
472  0.124896       0.6   0.000000  0.333333       1.0        0.0       0.0   

     hotwaterheating  airconditioning   parking  prefarea  
22               0.0              1.0  0.333333       0.0  
41               0.0              1.0  0.000000       1.0  
91               0.0              0.0  0.666667       1.0  
118              0.0              1.0  0.000000       1.0  
472              0.0              0.0  1.000000       0.0

In [14]:
y_Newtrain.head()

22     0.596970
41     0.527273
91     0.404242
118    0.363636
472    0.109091
Name: price, dtype: float64

In [15]:
y = y_Newtrain.values
print('y = ', y[: 5])

y =  [0.5969697  0.52727273 0.40424242 0.36363636 0.10909091]


In [16]:
# getting the input values from each column and putting them as a separate variable for training set

X1 = df_Newtrain.values[:, 0]
X2 = df_Newtrain.values[:, 1]
X3 = df_Newtrain.values[:, 2]
X4 = df_Newtrain.values[:, 3]
X5 = df_Newtrain.values[:, 4]
X6 = df_Newtrain.values[:, 5]
X7 = df_Newtrain.values[:, 6]
X8 = df_Newtrain.values[:, 7]
X9 = df_Newtrain.values[:, 8]
X10 = df_Newtrain.values[:, 9]
X11 = df_Newtrain.values[:, 10]

print('X1 = ', X1[: 5])
print('X2 = ', X2[: 5])
print('X3 = ', X3[: 5])
print('X4 = ', X4[: 5])
print('X5 = ', X5[: 5])
print('X6 = ', X6[: 5])
print('X7 = ', X7[: 5])
print('X8 = ', X8[: 5])
print('X9 = ', X9[: 5])
print('X10 = ', X10[: 5])
print('X11 = ', X11[: 5])

X1 =  [0.4326093  0.31495405 0.34210526 0.31913116 0.12489557]
X2 =  [0.4 0.4 0.2 0.4 0.6]
X3 =  [0.         0.33333333 0.         0.         0.        ]
X4 =  [0.         1.         0.         0.         0.33333333]
X5 =  [1. 1. 1. 1. 1.]
X6 =  [1. 0. 1. 0. 0.]
X7 =  [1. 0. 1. 1. 0.]
X8 =  [0. 0. 0. 0. 0.]
X9 =  [1. 1. 0. 1. 0.]
X10 =  [0.33333333 0.         0.66666667 0.         1.        ]
X11 =  [0. 1. 1. 1. 0.]


In [17]:
m = len(X_Newtrain)
X_0 = np.ones((m, 1))
X_0 [: 5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [18]:
# Converting 1D arrays of training X's to 2D arrays

X_1 = X1.reshape(m, 1)
X_2 = X2.reshape(m, 1)
X_3 = X3.reshape(m, 1)
X_4 = X4.reshape(m, 1)
X_5 = X5.reshape(m, 1)
X_6 = X6.reshape(m, 1)
X_7 = X7.reshape(m, 1)
X_8 = X8.reshape(m, 1)
X_9 = X9.reshape(m, 1)
X_10 = X10.reshape(m, 1)
X_11 = X11.reshape(m, 1)

print('X_1 = ', X_1[: 5])
print('X_2 = ', X_2[: 5])
print('X_3 = ', X_3[: 5])
print('X_4 = ', X_4[: 5])
print('X_5 = ', X_5[: 5])
print('X_6 = ', X_6[: 5])
print('X_7 = ', X_7[: 5])
print('X_8 = ', X_8[: 5])
print('X_9 = ', X_9[: 5])
print('X_10 = ', X_10[: 5])
print('X_11 = ', X_11[: 5])

X_1 =  [[0.4326093 ]
 [0.31495405]
 [0.34210526]
 [0.31913116]
 [0.12489557]]
X_2 =  [[0.4]
 [0.4]
 [0.2]
 [0.4]
 [0.6]]
X_3 =  [[0.        ]
 [0.33333333]
 [0.        ]
 [0.        ]
 [0.        ]]
X_4 =  [[0.        ]
 [1.        ]
 [0.        ]
 [0.        ]
 [0.33333333]]
X_5 =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
X_6 =  [[1.]
 [0.]
 [1.]
 [0.]
 [0.]]
X_7 =  [[1.]
 [0.]
 [1.]
 [1.]
 [0.]]
X_8 =  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
X_9 =  [[1.]
 [1.]
 [0.]
 [1.]
 [0.]]
X_10 =  [[0.33333333]
 [0.        ]
 [0.66666667]
 [0.        ]
 [1.        ]]
X_11 =  [[0.]
 [1.]
 [1.]
 [1.]
 [0.]]


In [19]:
# Stacking X_0 through X_11 horizotally
# This is the final X Matrix for training

X = np.hstack((X_0, X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11))
X [: 5]

array([[1.        , 0.4326093 , 0.4       , 0.        , 0.        ,
        1.        , 1.        , 1.        , 0.        , 1.        ,
        0.33333333, 0.        ],
       [1.        , 0.31495405, 0.4       , 0.33333333, 1.        ,
        1.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 1.        ],
       [1.        , 0.34210526, 0.2       , 0.        , 0.        ,
        1.        , 1.        , 1.        , 0.        , 0.        ,
        0.66666667, 1.        ],
       [1.        , 0.31913116, 0.4       , 0.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 1.        ],
       [1.        , 0.12489557, 0.6       , 0.        , 0.33333333,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ]])

In [20]:
y_Newtest = df_Newtest.pop('price')
X_Newtest = df_Newtest

In [21]:
X_Newtest.head()

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
265  0.088172  0.333333        0.0  0.333333       1.0        0.0       0.0   
54   0.311828  0.333333        0.5  0.333333       1.0        1.0       0.0   
171  0.617849  0.333333        0.0  0.000000       1.0        0.0       0.0   
244  0.263082  0.333333        0.0  0.333333       1.0        1.0       1.0   
268  0.236559  0.666667        0.0  0.333333       1.0        0.0       0.0   

     hotwaterheating  airconditioning   parking  prefarea  
265              0.0              0.0  0.000000       1.0  
54               0.0              1.0  0.333333       0.0  
171              0.0              0.0  0.333333       1.0  
244              0.0              0.0  0.000000       1.0  
268              0.0              1.0  0.000000       0.0

In [22]:
y_Newtest.head()

265    0.248485
54     0.531987
171    0.329966
244    0.262626
268    0.246465
Name: price, dtype: float64

In [23]:
y_test = y_Newtest.values
print('y_test = ', y_test[: 5])

y_test =  [0.24848485 0.53198653 0.32996633 0.26262626 0.24646465]


In [24]:
# getting the input values from each column and putting them as a separate variable for validation set

X1_test = df_Newtest.values[:, 0]
X2_test = df_Newtest.values[:, 1]
X3_test = df_Newtest.values[:, 2]
X4_test = df_Newtest.values[:, 3]
X5_test = df_Newtest.values[:, 4]
X6_test = df_Newtest.values[:, 5]
X7_test = df_Newtest.values[:, 6]
X8_test = df_Newtest.values[:, 7]
X9_test = df_Newtest.values[:, 8]
X10_test = df_Newtest.values[:, 9]
X11_test = df_Newtest.values[:, 10]

In [25]:
m_test = len(X_Newtest)
X_0_test = np.ones((m_test, 1))

In [26]:
# Converting 1D arrays of validation X's to 2D arrays

X_1_test = X1_test.reshape(m_test, 1)
X_2_test = X2_test.reshape(m_test, 1)
X_3_test = X3_test.reshape(m_test, 1)
X_4_test = X4_test.reshape(m_test, 1)
X_5_test = X5_test.reshape(m_test, 1)
X_6_test = X6_test.reshape(m_test, 1)
X_7_test = X7_test.reshape(m_test, 1)
X_8_test = X8_test.reshape(m_test, 1)
X_9_test = X9_test.reshape(m_test, 1)
X_10_test = X10_test.reshape(m_test, 1)
X_11_test = X11_test.reshape(m_test, 1)

In [27]:
# Stacking X_0_test through X_11_test horizotally
# This is the final X Matrix for validation

X_test = np.hstack((X_0_test, X_1_test, X_2_test, X_3_test, X_4_test, X_5_test, X_6_test, X_7_test, X_8_test, X_9_test, X_10_test, X_11_test))
X_test [: 5]

array([[1.        , 0.08817204, 0.33333333, 0.        , 0.33333333,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        ],
       [1.        , 0.31182796, 0.33333333, 0.5       , 0.33333333,
        1.        , 1.        , 0.        , 0.        , 1.        ,
        0.33333333, 0.        ],
       [1.        , 0.61784946, 0.33333333, 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.33333333, 1.        ],
       [1.        , 0.26308244, 0.33333333, 0.        , 0.33333333,
        1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 1.        ],
       [1.        , 0.23655914, 0.66666667, 0.        , 0.33333333,
        1.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        ]])

In [28]:
from sklearn.svm import SVR

svr_lin = SVR(kernel='linear', C=1e3)
svr_lin.fit(X, y)
y_pred = svr_lin.predict(X_test)

In [29]:
y_pred[0:9]

array([0.1775899 , 0.50148198, 0.32757082, 0.30337668, 0.25598343,
       0.17643201, 0.6167624 , 0.40122357, 0.17036538])

In [30]:
errors = np.subtract(y_pred, y_test)
sqrErrors = np.square(errors)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss

0.0062063289402495905

In [31]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(X, y)
y_pred = svr_rbf.predict(X_test)

In [32]:
errors = np.subtract(y_pred, y_test)
sqrErrors = np.square(errors)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss

0.013733033485657783

In [33]:
svr_poly = SVR(kernel='poly', C=1e3, degree=2)
svr_poly.fit(X, y)
y_pred = svr_poly.predict(X_test)

In [34]:
errors = np.subtract(y_pred, y_test)
sqrErrors = np.square(errors)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss

0.00808045482925889