<a href="https://colab.research.google.com/github/ismachy/Introduction-to-ML/blob/main/HW_5_Q_02_a_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import torch
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
url = 'https://raw.githubusercontent.com/hurricane195/Intro-to-Machine-Learning/Datasets/Housing.csv'
housing = pd.read_csv(url)
housing.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [3]:
num_vars = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']
df_new = housing[num_vars]

In [4]:
scaler = MinMaxScaler()
df_new[num_vars] = scaler.fit_transform(df_new[num_vars])
df_new.head()

<ipython-input-4-e90be4113ded>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[num_vars] = scaler.fit_transform(df_new[num_vars])


price      area  bedrooms  bathrooms   stories   parking
0  1.000000  0.396564       0.6   0.333333  0.666667  0.666667
1  0.909091  0.502405       0.6   1.000000  1.000000  1.000000
2  0.909091  0.571134       0.4   0.333333  0.333333  0.666667
3  0.906061  0.402062       0.6   0.333333  0.333333  1.000000
4  0.836364  0.396564       0.6   0.000000  0.333333  0.666667

In [5]:
X = df_new.iloc[:, 1:6].values
Y = df_new.iloc[:, 0].values

In [6]:
X = torch.tensor(X)
Y = torch.tensor(Y)

In [7]:
def model(X, W1, W2, W3, W4, W5, B):
    return W5*X[:,4] + W4*X[:,3] + W3*X[:,2] + W2*X[:,1] + W1*X[:,0] + B

In [8]:
def loss_fn(Y_p, Y):
    squared_diffs = (Y_p - Y)**2
    return squared_diffs.mean()

In [9]:
W1 = torch.ones(())
W2 = torch.ones(())
W3 = torch.ones(())
W4 = torch.ones(())
W5 = torch.ones(())
B = torch.zeros(())

In [10]:
n_samples = X.shape[0]
n_val = int(0.2 * n_samples)
shuffled_indices = torch.randperm(n_samples)
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

In [11]:
train_X = X[train_indices]
train_Y = Y[train_indices]
val_X = X[val_indices]
val_Y = Y[val_indices]

In [12]:
def training_loop(n_epochs, optimizer, params, train_X, val_X, train_Y, val_Y):

    for epoch in range(1, n_epochs + 1):
        train_Y_p = model(train_X, *params)
        train_loss = loss_fn(train_Y_p, train_Y)

        val_Y_p = model(val_X, *params)
        val_loss = loss_fn(val_Y_p, val_Y)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params

In [13]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0117, Validation loss 0.0109
Epoch 1000, Training loss 0.0117, Validation loss 0.0109
Epoch 1500, Training loss 0.0117, Validation loss 0.0109
Epoch 2000, Training loss 0.0117, Validation loss 0.0109
Epoch 2500, Training loss 0.0117, Validation loss 0.0109
Epoch 3000, Training loss 0.0117, Validation loss 0.0109
Epoch 3500, Training loss 0.0117, Validation loss 0.0109
Epoch 4000, Training loss 0.0117, Validation loss 0.0109
Epoch 4500, Training loss 0.0117, Validation loss 0.0109
Epoch 5000, Training loss 0.0117, Validation loss 0.0109


tensor([0.4045, 0.0721, 0.3065, 0.1457, 0.1050, 0.0464], requires_grad=True)

In [14]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0136, Validation loss 0.0122
Epoch 1000, Training loss 0.0118, Validation loss 0.0109
Epoch 1500, Training loss 0.0117, Validation loss 0.0109
Epoch 2000, Training loss 0.0117, Validation loss 0.0109
Epoch 2500, Training loss 0.0117, Validation loss 0.0109
Epoch 3000, Training loss 0.0117, Validation loss 0.0109
Epoch 3500, Training loss 0.0117, Validation loss 0.0109
Epoch 4000, Training loss 0.0117, Validation loss 0.0109
Epoch 4500, Training loss 0.0117, Validation loss 0.0109
Epoch 5000, Training loss 0.0117, Validation loss 0.0109


tensor([0.4045, 0.0721, 0.3065, 0.1457, 0.1050, 0.0464], requires_grad=True)

In [15]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-3
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.1268, Validation loss 0.1274
Epoch 1000, Training loss 0.0514, Validation loss 0.0527
Epoch 1500, Training loss 0.0346, Validation loss 0.0348
Epoch 2000, Training loss 0.0236, Validation loss 0.0231
Epoch 2500, Training loss 0.0178, Validation loss 0.0167
Epoch 3000, Training loss 0.0151, Validation loss 0.0137
Epoch 3500, Training loss 0.0138, Validation loss 0.0124
Epoch 4000, Training loss 0.0130, Validation loss 0.0117
Epoch 4500, Training loss 0.0124, Validation loss 0.0113
Epoch 5000, Training loss 0.0120, Validation loss 0.0110


tensor([ 0.4264,  0.2131,  0.2624,  0.1283,  0.0989, -0.0054],
       requires_grad=True)

In [16]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 1.0047, Validation loss 0.9726
Epoch 1000, Training loss 0.8076, Validation loss 0.7830
Epoch 1500, Training loss 0.6416, Validation loss 0.6233
Epoch 2000, Training loss 0.5030, Validation loss 0.4900
Epoch 2500, Training loss 0.3889, Validation loss 0.3801
Epoch 3000, Training loss 0.2967, Validation loss 0.2913
Epoch 3500, Training loss 0.2239, Validation loss 0.2211
Epoch 4000, Training loss 0.1683, Validation loss 0.1675
Epoch 4500, Training loss 0.1276, Validation loss 0.1281
Epoch 5000, Training loss 0.0993, Validation loss 0.1006


tensor([ 0.6144,  0.6147,  0.5919,  0.5970,  0.5944, -0.3700],
       requires_grad=True)

In [18]:
#SGD

In [19]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0119, Validation loss 0.0109
Epoch 1000, Training loss 0.0117, Validation loss 0.0109
Epoch 1500, Training loss 0.0117, Validation loss 0.0109
Epoch 2000, Training loss 0.0117, Validation loss 0.0109
Epoch 2500, Training loss 0.0117, Validation loss 0.0109
Epoch 3000, Training loss 0.0117, Validation loss 0.0109
Epoch 3500, Training loss 0.0117, Validation loss 0.0109
Epoch 4000, Training loss 0.0117, Validation loss 0.0109
Epoch 4500, Training loss 0.0117, Validation loss 0.0109
Epoch 5000, Training loss 0.0117, Validation loss 0.0109


tensor([0.4045, 0.0721, 0.3065, 0.1457, 0.1050, 0.0464], requires_grad=True)

In [20]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0499, Validation loss 0.0486
Epoch 1000, Training loss 0.0226, Validation loss 0.0212
Epoch 1500, Training loss 0.0160, Validation loss 0.0146
Epoch 2000, Training loss 0.0140, Validation loss 0.0126
Epoch 2500, Training loss 0.0131, Validation loss 0.0118
Epoch 3000, Training loss 0.0126, Validation loss 0.0114
Epoch 3500, Training loss 0.0123, Validation loss 0.0112
Epoch 4000, Training loss 0.0121, Validation loss 0.0110
Epoch 4500, Training loss 0.0120, Validation loss 0.0110
Epoch 5000, Training loss 0.0119, Validation loss 0.0109


tensor([0.4480, 0.1713, 0.2895, 0.1256, 0.0893, 0.0072], requires_grad=True)

In [21]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-3
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.2221, Validation loss 0.2149
Epoch 1000, Training loss 0.1381, Validation loss 0.1360
Epoch 1500, Training loss 0.1170, Validation loss 0.1157
Epoch 2000, Training loss 0.1021, Validation loss 0.1010
Epoch 2500, Training loss 0.0897, Validation loss 0.0886
Epoch 3000, Training loss 0.0791, Validation loss 0.0779
Epoch 3500, Training loss 0.0700, Validation loss 0.0688
Epoch 4000, Training loss 0.0622, Validation loss 0.0610
Epoch 4500, Training loss 0.0555, Validation loss 0.0543
Epoch 5000, Training loss 0.0498, Validation loss 0.0486


tensor([ 0.6932,  0.5592,  0.6444,  0.3671,  0.3605, -0.3917],
       requires_grad=True)

In [22]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.9806, Validation loss 0.9468
Epoch 1000, Training loss 0.7848, Validation loss 0.7569
Epoch 1500, Training loss 0.6355, Validation loss 0.6122
Epoch 2000, Training loss 0.5214, Validation loss 0.5019
Epoch 2500, Training loss 0.4341, Validation loss 0.4178
Epoch 3000, Training loss 0.3672, Validation loss 0.3535
Epoch 3500, Training loss 0.3159, Validation loss 0.3043
Epoch 4000, Training loss 0.2763, Validation loss 0.2664
Epoch 4500, Training loss 0.2457, Validation loss 0.2373
Epoch 5000, Training loss 0.2220, Validation loss 0.2148


tensor([ 0.8461,  0.7575,  0.9028,  0.7782,  0.7920, -0.5077],
       requires_grad=True)