<a href="https://colab.research.google.com/github/ismachy/Introduction-to-ML/blob/main/HW_5_Q_03_a_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import torch
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
housing = pd.read_csv('/content/drive/MyDrive/dataset/Housing2.csv')
housing

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:
categorical_columns = housing.select_dtypes(include=['object']).columns

In [ ]:
categorical_columns

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for column in categorical_columns:
    housing[column] = label_encoder.fit_transform(housing[column])


In [ ]:
housing

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
..                ...  
540                 2  
541                 1  
542                 2  
543                 0  
544                 2  

[545 rows x 13 columns]

In [ ]:
num_vars = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking','mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus']
df_new = housing[num_vars]

In [ ]:
scaler = MinMaxScaler()
df_new[num_vars] = scaler.fit_transform(df_new[num_vars])
df_new.head()

price      area  bedrooms  bathrooms   stories   parking  mainroad  \
0  1.000000  0.396564       0.6   0.333333  0.666667  0.666667       1.0   
1  0.909091  0.502405       0.6   1.000000  1.000000  1.000000       1.0   
2  0.909091  0.571134       0.4   0.333333  0.333333  0.666667       1.0   
3  0.906061  0.402062       0.6   0.333333  0.333333  1.000000       1.0   
4  0.836364  0.396564       0.6   0.000000  0.333333  0.666667       1.0   

   guestroom  basement  hotwaterheating  airconditioning  prefarea  \
0        0.0       0.0              0.0              1.0       1.0   
1        0.0       0.0              0.0              1.0       0.0   
2        0.0       1.0              0.0              0.0       1.0   
3        0.0       1.0              0.0              1.0       1.0   
4        1.0       1.0              0.0              1.0       0.0   

   furnishingstatus  
0               0.0  
1               0.0  
2               0.5  
3               0.0  
4               0.0

In [ ]:
X = df_new.iloc[:, 1:13].values
Y = df_new.iloc[:, 0].values

In [ ]:
X = torch.tensor(X)
Y = torch.tensor(Y)

In [ ]:
def model(X, W1, W2, W3, W4, W5, W6, W7, W8, W9, W10, W11, W12, B):
    return (
        W12 * X[:, 11] +
        W11 * X[:, 10] +
        W10 * X[:, 9] +
        W9 * X[:, 8] +
        W8 * X[:, 7] +
        W7 * X[:, 6] +
        W6 * X[:, 5] +
        W5 * X[:, 4] +
        W4 * X[:, 3] +
        W3 * X[:, 2] +
        W2 * X[:, 1] +
        W1 * X[:, 0] +
        B
    )


In [ ]:
def loss_fn(Y_p, Y):
    squared_diffs = (Y_p - Y)**2
    return squared_diffs.mean()

In [ ]:
# Create weight parameters W1 to W13
W1 = torch.ones(1, requires_grad=True)
W2 = torch.ones(1, requires_grad=True)
W3 = torch.ones(1, requires_grad=True)
W4 = torch.ones(1, requires_grad=True)
W5 = torch.ones(1, requires_grad=True)
W6 = torch.ones(1, requires_grad=True)
W7 = torch.ones(1, requires_grad=True)
W8 = torch.ones(1, requires_grad=True)
W9 = torch.ones(1, requires_grad=True)
W10 = torch.ones(1, requires_grad=True)
W11 = torch.ones(1, requires_grad=True)
W12 = torch.ones(1, requires_grad=True)

# Create bias parameter B
B = torch.zeros(1, requires_grad=True)
# B = torch.zeros(())

In [ ]:
n_samples = X.shape[0]
n_val = int(0.2 * n_samples)
shuffled_indices = torch.randperm(n_samples)
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

In [ ]:
train_X = X[train_indices]
train_Y = Y[train_indices]
val_X = X[val_indices]
val_Y = Y[val_indices]

In [ ]:
def training_loop(n_epochs, optimizer, params, train_X, val_X, train_Y, val_Y):

    for epoch in range(1, n_epochs + 1):
        train_Y_p = model(train_X, *params)
        train_loss = loss_fn(train_Y_p, train_Y)

        val_Y_p = model(val_X, *params)
        val_loss = loss_fn(val_Y_p, val_Y)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0083, Validation loss 0.0093
Epoch 1000, Training loss 0.0083, Validation loss 0.0093
Epoch 1500, Training loss 0.0083, Validation loss 0.0093
Epoch 2000, Training loss 0.0083, Validation loss 0.0093
Epoch 2500, Training loss 0.0083, Validation loss 0.0093
Epoch 3000, Training loss 0.0083, Validation loss 0.0093
Epoch 3500, Training loss 0.0083, Validation loss 0.0093
Epoch 4000, Training loss 0.0083, Validation loss 0.0093
Epoch 4500, Training loss 0.0083, Validation loss 0.0093
Epoch 5000, Training loss 0.0083, Validation loss 0.0093


tensor([ 0.2807,  0.0348,  0.2740,  0.1264,  0.0905,  0.0409,  0.0164,  0.0369,
         0.0970,  0.0722,  0.0550, -0.0352,  0.0242], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0283, Validation loss 0.0397
Epoch 1000, Training loss 0.0164, Validation loss 0.0220
Epoch 1500, Training loss 0.0115, Validation loss 0.0139
Epoch 2000, Training loss 0.0094, Validation loss 0.0107
Epoch 2500, Training loss 0.0086, Validation loss 0.0096
Epoch 3000, Training loss 0.0083, Validation loss 0.0093
Epoch 3500, Training loss 0.0083, Validation loss 0.0093
Epoch 4000, Training loss 0.0083, Validation loss 0.0093
Epoch 4500, Training loss 0.0083, Validation loss 0.0093
Epoch 5000, Training loss 0.0083, Validation loss 0.0093


tensor([ 0.2807,  0.0349,  0.2740,  0.1264,  0.0905,  0.0409,  0.0164,  0.0369,
         0.0970,  0.0722,  0.0550, -0.0352,  0.0241], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-3
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 2.8113, Validation loss 2.9473
Epoch 1000, Training loss 0.3275, Validation loss 0.3651
Epoch 1500, Training loss 0.0693, Validation loss 0.0858
Epoch 2000, Training loss 0.0493, Validation loss 0.0631
Epoch 2500, Training loss 0.0403, Validation loss 0.0538
Epoch 3000, Training loss 0.0341, Validation loss 0.0470
Epoch 3500, Training loss 0.0296, Validation loss 0.0414
Epoch 4000, Training loss 0.0259, Validation loss 0.0363
Epoch 4500, Training loss 0.0225, Validation loss 0.0314
Epoch 5000, Training loss 0.0194, Validation loss 0.0268


tensor([ 0.3397,  0.3750,  0.2158,  0.1642,  0.1271,  0.2519,  0.0010,  0.0917,
         0.1153,  0.0919,  0.0357,  0.1444, -0.4509], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 12.1381, Validation loss 12.5376
Epoch 1000, Training loss 10.5489, Validation loss 10.9068
Epoch 1500, Training loss 9.1102, Validation loss 9.4297
Epoch 2000, Training loss 7.8090, Validation loss 8.0930
Epoch 2500, Training loss 6.6350, Validation loss 6.8863
Epoch 3000, Training loss 5.5796, Validation loss 5.8007
Epoch 3500, Training loss 4.6360, Validation loss 4.8293
Epoch 4000, Training loss 3.7984, Validation loss 3.9661
Epoch 4500, Training loss 3.0617, Validation loss 3.2061
Epoch 5000, Training loss 2.4213, Validation loss 2.5446


tensor([ 0.5595,  0.5600,  0.5583,  0.5590,  0.5584,  0.5597,  0.5545,  0.5564,
         0.5586,  0.5570,  0.5556,  0.5601, -0.4392], requires_grad=True)

In [ ]:
#SGD

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0088, Validation loss 0.0095
Epoch 1000, Training loss 0.0083, Validation loss 0.0092
Epoch 1500, Training loss 0.0083, Validation loss 0.0093
Epoch 2000, Training loss 0.0083, Validation loss 0.0093
Epoch 2500, Training loss 0.0083, Validation loss 0.0093
Epoch 3000, Training loss 0.0083, Validation loss 0.0093
Epoch 3500, Training loss 0.0083, Validation loss 0.0093
Epoch 4000, Training loss 0.0083, Validation loss 0.0093
Epoch 4500, Training loss 0.0083, Validation loss 0.0093
Epoch 5000, Training loss 0.0083, Validation loss 0.0093


tensor([ 0.2807,  0.0348,  0.2740,  0.1264,  0.0905,  0.0409,  0.0164,  0.0369,
         0.0970,  0.0722,  0.0550, -0.0352,  0.0242], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0732, Validation loss 0.0826
Epoch 1000, Training loss 0.0321, Validation loss 0.0411
Epoch 1500, Training loss 0.0191, Validation loss 0.0253
Epoch 2000, Training loss 0.0139, Validation loss 0.0180
Epoch 2500, Training loss 0.0116, Validation loss 0.0142
Epoch 3000, Training loss 0.0104, Validation loss 0.0121
Epoch 3500, Training loss 0.0097, Validation loss 0.0109
Epoch 4000, Training loss 0.0093, Validation loss 0.0102
Epoch 4500, Training loss 0.0090, Validation loss 0.0098
Epoch 5000, Training loss 0.0088, Validation loss 0.0095


tensor([ 0.3555,  0.1897,  0.2610,  0.0965,  0.0699,  0.0591,  0.0132,  0.0374,
         0.1037,  0.0726,  0.0476, -0.0182, -0.0654], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-3
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.4452, Validation loss 0.4347
Epoch 1000, Training loss 0.2852, Validation loss 0.2798
Epoch 1500, Training loss 0.2171, Validation loss 0.2173
Epoch 2000, Training loss 0.1727, Validation loss 0.1762
Epoch 2500, Training loss 0.1423, Validation loss 0.1480
Epoch 3000, Training loss 0.1206, Validation loss 0.1276
Epoch 3500, Training loss 0.1044, Validation loss 0.1123
Epoch 4000, Training loss 0.0917, Validation loss 0.1003
Epoch 4500, Training loss 0.0816, Validation loss 0.0906
Epoch 5000, Training loss 0.0732, Validation loss 0.0826


tensor([ 0.5858,  0.4490,  0.5929,  0.3186,  0.3294,  0.1336,  0.1278,  0.0842,
         0.6440,  0.0906,  0.1165,  0.3630, -0.7557], requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 8.2122, Validation loss 8.4721
Epoch 1000, Training loss 4.9322, Validation loss 5.0818
Epoch 1500, Training loss 3.0390, Validation loss 3.1228
Epoch 2000, Training loss 1.9434, Validation loss 1.9877
Epoch 2500, Training loss 1.3065, Validation loss 1.3272
Epoch 3000, Training loss 0.9338, Validation loss 0.9403
Epoch 3500, Training loss 0.7131, Validation loss 0.7113
Epoch 4000, Training loss 0.5801, Validation loss 0.5736
Epoch 4500, Training loss 0.4979, Validation loss 0.4888
Epoch 5000, Training loss 0.4452, Validation loss 0.4348


tensor([ 0.6776,  0.5113,  0.8262,  0.5978,  0.6446, -0.0345,  0.6227,  0.4182,
         0.9135,  0.4494,  0.5450,  0.4207, -1.1180], requires_grad=True)